# Ez a yml file tartalmazza a Docker konténer környezet inicializálásához szükséges paramétereket
# A következő parancs futtatásával -> docker compose -f common/docker/postgres-compose.yml
# Létrejön egy Postgres adatbázist és egy PgAdmin grafikus adatbáziskezelő felületet tartalmaző könténer

version: '3.9'
services:
#  adatbázis és alapvető paraméterei
#  itt érjük el: jdbc:postgresql://localhost:25431/car
#  lent megadott user, password és db-névvel
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "25431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
# adatbázis kezelő grafikus felület és alapvető paraméterei
#  itt érjük el böngészőből: http://localhost:5060/
#  lent megadott e-mail és jelszóval lehet bejelentkezni
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5049:80"

volumes:
  pgdata:
